version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  ## ==============================================
  local-init:
    cmds:
      # - go mod download
      # - go run cmd/main.go
  local-run:
    cmds:
      - go run cmd/main.go
  local-test1:
    cmds:
      - |
        curl -X POST "http://localhost:3000/api/incidents" \
          -H "Content-Type: application/json" \
          -d '{
            "receiver": "webhook-incident",
            "status": "firing",
            "alerts": [
              {
                "status": "firing",
                "labels": {
                  "alertname": "HighMemoryUsage",
                  "instance": "server-prod-01",
                  "severity": "critical"
                },
                "annotations": {
                  "summary": "Memory usage is above 90%",
                  "description": "Server server-prod-01 memory usage is at 95%"
                },
                "startsAt": "2025-12-10T09:00:00Z"
              }
            ],
            "commonLabels": {
              "alertname": "HighMemoryUsage",
              "severity": "critical",
              "instance": "server-prod-01"
            },
            "commonAnnotations": {
              "summary": "Memory usage is above 90%",
              "description": "Server server-prod-01 memory usage is at 95%"
            }
          }'

  # Check scheduler status
  local-scheduler-status:
    cmds:
      - curl -s "http://localhost:3000/api/scheduler/status" | jq .
  ## ==============================================
